name: Notify via Email on Commit

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 New File Released on Parental Portal"
          to: "itz.rth@gmail.com"
          from: "SSM BOT"
          body: |
            A New File has been released on the Parental Portal!
            📅 **Date:** ${{ github.event.head_commit.timestamp }}
            
            📢 **Message:** ${{ github.event.head_commit.message }}
            🔗 **View Updates in** https://github.com/itzRoheith/ssm
            ✅ *You are receiving this notification automatically via GitHub Actions!*
          content_type: text/markdown
